// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	   int n = Integer.parseInt(args[0]);
	   double tempRandom;
	   int countBig = 0;
	   int countSmall=0;
	    double ratio;
	   for(int i = 0 ; i < n ; i++){
		tempRandom = Math.random();
		if(tempRandom>0.5)
		countBig++;
        else
		countSmall++;
	   }
	   if(countBig!=0&&countSmall!=0){
	    ratio = ((double) countBig)/countSmall;
	    System.out.println("> 0.5: " + countBig + " times");
		System.out.println("<= 0.5: " + countSmall + " times");
        System.out.println( "ratio: " + ratio);
	}
	else{
		 System.out.println("> 0.5:  " + countBig + " times");
		 System.out.println("<= 0.5:  " + countSmall + " times");
	}




}
}
